import type { Metadata } from "next";
import { Marcellus, Sora } from "next/font/google";
import SmoothScroller from "@/components/SmoothScroller";
import "./globals.css";

const marcellus = Marcellus({
  variable: "--font-marcellus",
  subsets: ["latin"],
  weight: "400",
});

const sora = Sora({
  variable: "--font-sora",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      className={`${marcellus.variable} ${sora.variable} antialiased`}
    >
      <body>
        <SmoothScroller>
          {children}
        </SmoothScroller>
      </body>
    </html>
  );
}
